name: Build and Release macOS App

on:
  push:
    tags: ['v*']

env:
  APP_NAME: "VTS"
  BUNDLE_ID: "com.voicetypestudio.app"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: macos-15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Make build script executable
      run: chmod +x scripts/build-dmg.sh
    
    - name: Build, Sign, and Notarize DMG
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        APP_NAME: ${{ env.APP_NAME }}
        BUNDLE_ID: ${{ env.BUNDLE_ID }}
        GITHUB_ACTIONS: true
        GITHUB_REF: ${{ github.ref }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: ./scripts/build-dmg.sh

    - name: Extract version info
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION_NUMBER=${VERSION#v}  # Remove 'v' prefix
        
        # Get the previous tag for comparison
        PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -v "^${VERSION}$" | head -n1)
        if [ -z "$PREVIOUS_TAG" ]; then
          PREVIOUS_TAG="v0.2.2"  # Fallback for first release
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "version_number=$VERSION_NUMBER" >> $GITHUB_OUTPUT
        echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION_NUMBER"
        echo "Previous tag: $PREVIOUS_TAG"

    - name: Download Sparkle Tools and Sign DMG
      env:
        SPARKLE_PRIVATE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY }}
        VERSION_NUMBER: ${{ steps.get_version.outputs.version_number }}
        APP_NAME: ${{ env.APP_NAME }}
      run: |          
        echo "🔐 Signing DMG with Sparkle private key..."
        
        # Create temporary directory for Sparkle tools
        TEMP_DIR=$(mktemp -d)
        echo "📁 Created temp directory: $TEMP_DIR"
        cd "$TEMP_DIR"
        
        # Download Sparkle tools
        SPARKLE_VERSION="2.6.4"
        SPARKLE_URL="https://github.com/sparkle-project/Sparkle/releases/download/${SPARKLE_VERSION}/Sparkle-${SPARKLE_VERSION}.tar.xz"
        echo "📥 Downloading Sparkle tools from: $SPARKLE_URL"
        
        if ! curl -L -o sparkle.tar.xz "$SPARKLE_URL"; then
          echo "❌ Failed to download Sparkle tools"
          exit 1
        fi
        
        echo "📦 Extracting Sparkle tools..."
        if ! tar -xf sparkle.tar.xz; then
          echo "❌ Failed to extract Sparkle tools"
          echo "📄 Archive contents:"
          tar -tf sparkle.tar.xz || echo "Cannot list archive contents"
          exit 1
        fi
        
        echo "📂 Contents after extraction:"
        ls -la
        
        # Check for bin directory and sign_update tool
        if [[ ! -d "bin" ]]; then
          echo "❌ bin directory not found after extraction"
          echo "📂 Available directories:"
          find . -type d -name "*" | head -10
          exit 1
        fi
        
        if [[ ! -f "bin/sign-update" ]]; then
          echo "❌ sign-update tool not found in bin directory"
          echo "📂 Contents of bin directory:"
          ls -la bin/
          exit 1
        fi
        
        # Make sign-update executable
        chmod +x bin/sign-update
        
        # Create private key file
        echo "$SPARKLE_PRIVATE_KEY" > private_key
        
        # Sign the DMG and generate signature
        DMG_PATH="${GITHUB_WORKSPACE}/${APP_NAME}-${VERSION_NUMBER}-Universal.dmg"
        echo "🔍 Looking for DMG at: $DMG_PATH"
        
        if [[ -f "$DMG_PATH" ]]; then
          echo "✅ DMG file found, generating signature..."
          
          # Generate signature with error handling (using correct syntax)
          if ! SIGNATURE=$(./bin/sign-update -p --ed-key-file private_key "$DMG_PATH"); then
            echo "❌ Failed to generate signature"
            echo "🔧 Debugging info:"
            file "$DMG_PATH"
            ls -la "$DMG_PATH"
            ./bin/sign-update --help || echo "No help available"
            exit 1
          fi
          
          echo "Generated signature: $SIGNATURE"
          
          # Validate signature is not empty
          if [[ -z "$SIGNATURE" ]]; then
            echo "❌ Generated signature is empty"
            exit 1
          fi
          
          # Save signature to file for the appcast
          echo "$SIGNATURE" > "${GITHUB_WORKSPACE}/${APP_NAME}-${VERSION_NUMBER}-Universal.dmg.sig"
          
          # Also create a JSON file with release metadata for GitHub Pages
          cat > "${GITHUB_WORKSPACE}/release-metadata.json" << EOF
        {
          "version": "${VERSION_NUMBER}",
          "dmg_name": "${APP_NAME}-${VERSION_NUMBER}-Universal.dmg",
          "sparkle_signature": "$SIGNATURE",
          "release_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        }
        EOF
          
          echo "✅ Successfully signed DMG with Sparkle signature"
        else
          echo "❌ DMG file not found: $DMG_PATH"
          echo "📂 Available files in workspace:"
          ls -la "$GITHUB_WORKSPACE"/*.dmg || echo "No DMG files found"
          exit 1
        fi
        
        # Cleanup
        cd "$GITHUB_WORKSPACE"
        rm -rf "$TEMP_DIR"

    - name: Update Release with Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: ${{ env.APP_NAME }} ${{ steps.get_version.outputs.version_number }}
        draft: false
        prerelease: false
        body: |
          ### Download
          - **Universal Binary (Intel + Apple Silicon)**: Download the DMG below
          - **Minimum macOS Version**: 14.0 (Sonoma)
          
          ### Installation
          1. Download the DMG file
          2. Open the DMG
          3. Drag ${{ env.APP_NAME }} to Applications folder
          4. Launch from Applications
          
          ### Verification
          This release is code-signed and notarized by Apple for security.
          
          ### Changes
          See the [commit history](https://github.com/${{ github.repository }}/compare/${{ steps.get_version.outputs.previous_tag }}...${{ steps.get_version.outputs.version }}) for detailed changes.
        files: |
          ${{ env.APP_NAME }}-${{ steps.get_version.outputs.version_number }}-Universal.dmg
          ${{ env.APP_NAME }}-${{ steps.get_version.outputs.version_number }}-Universal.dmg.sig
          checksums.txt
          release-metadata.json
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Success logs
      if: success()
      run: |
        echo "🎉 Release ${{ steps.get_version.outputs.version }} has been published!"
        echo "📡 GitHub Pages will automatically update the appcast feed."
        echo "🔗 Appcast URL: https://j05u3.github.io/VTS/appcast.xml"
